### ISSUE TITLE
Botão de like - erro

### ISSUE THREAD

**Issue by anacarolerthal** [anacarolerthal/blogging_system#5]
Subi o código da alteração de como curtir impacta no front, minha ideia era que curtir tornasse o botão de "curtir" em "descurtir" e vice-versa. Mas percebi depois que ele está alterando o botão de todos os posts. 

Não consegui resolver ainda

**Comment by palomavb** [comment]
Carol, resolvi o problema! 
Antes a função do_like estava implementando uma lógica de recarregar a main_page atualizando os botões de todos os posts, e a cada clique em um botão de like a página era atualizada novamente. 
Mudei um pouco a lógica, de forma que o clique no botão de like retorna uma resposta json e adicionei um script no html para atualizar apenas o botão do post curtido de acordo com essa resposta.
